.PHONY: clean All

All:
	@echo "----------Building project:[ desktop - Debug ]----------"
	@"$(MAKE)" -f  "desktop.mk" PreBuild && "$(MAKE)" -f  "desktop.mk"
clean:
	@echo "----------Cleaning project:[ desktop - Debug ]----------"
	@"$(MAKE)" -f  "desktop.mk" clean
