// This file is autogenerated -- do not edit.

static const char cmd_help_B58B[] CONSOLE_PROGMEM = ". (d - ) Pop and print as signed decimal.";
static const char cmd_help_73DE[] CONSOLE_PROGMEM = "U. (u - ) Pop and print as unsigned decimal, with leading `+'.";
static const char cmd_help_658F[] CONSOLE_PROGMEM = "$. (u - ) Pop and print as 4 hex digits with leading `$'.";
static const char cmd_help_66C9[] CONSOLE_PROGMEM = ".\" (s - ) Pop and print string.";
static const char cmd_help_B508[] CONSOLE_PROGMEM = "DEPTH ( - u) Push stack depth.";
static const char cmd_help_9F9C[] CONSOLE_PROGMEM = "CLEAR ( ... - <empty>) Remove all items from stack.";
static const char cmd_help_5C2C[] CONSOLE_PROGMEM = "DROP (x - ) Remove top item from stack.";
static const char cmd_help_90B7[] CONSOLE_PROGMEM = "HASH (s - u) Pop string and push hash value.";
static const char cmd_help_B58E[] CONSOLE_PROGMEM = "+ (x1 x2 - x3) Add: x3 = x1 + x2.";
static const char cmd_help_B588[] CONSOLE_PROGMEM = "- (x1 x2 - x3) Subtract: x3 = x1 - x2.";
static const char cmd_help_B58F[] CONSOLE_PROGMEM = "* (d1 d2 - d3) Signed multiply: d3 = d1 * d2.";
static const char cmd_help_6B97[] CONSOLE_PROGMEM = "RSHIFT (u1 n - u2) Logical bitwise shift right: u2 = u1 >> n.";
static const char cmd_help_B58A[] CONSOLE_PROGMEM = "/ (d1 d2 - d3) Signed dvide: d3 = d1 / d2.";
static const char cmd_help_73DF[] CONSOLE_PROGMEM = "U/ (u1 u2 - u3) Unsigned divide: u3 = u1 / u2.";
static const char cmd_help_7A79[] CONSOLE_PROGMEM = "NEGATE (d1 - d2) Negate signed value: d2 = -d1.";
static const char cmd_help_B586[] CONSOLE_PROGMEM = "# ( - ) Comment, rest of input ignored.";
static const char cmd_help_4069[] CONSOLE_PROGMEM = "RAISE (i - ) Raise value as exception.";
static const char cmd_help_C745[] CONSOLE_PROGMEM = "EXIT ( - ?) Exit console.";
static const char cmd_help_13B4[] CONSOLE_PROGMEM = "PICK (u - x) Copy stack item by index.";
static const char cmd_help_398B[] CONSOLE_PROGMEM = "OVER (x1 x2 - x1 x2 x1) Copy second stack item.";
static const char cmd_help_47B4[] CONSOLE_PROGMEM = "PRINT (x i - ) Call consolePrint(i, x).";
static const char cmd_help_B0B4[] CONSOLE_PROGMEM = "??HELP ( - ) Print (wordy) help for all commands.";
static const char cmd_help_74CB[] CONSOLE_PROGMEM = "?HELP ( - ) Print list of all commands.";
static const char cmd_help_7D54[] CONSOLE_PROGMEM = "HELP (s - ) Search for help on given command.";

static const char* const help_cmds[] CONSOLE_PROGMEM = {
    cmd_help_B58B,
    cmd_help_73DE,
    cmd_help_658F,
    cmd_help_66C9,
    cmd_help_B508,
    cmd_help_9F9C,
    cmd_help_5C2C,
    cmd_help_90B7,
    cmd_help_B58E,
    cmd_help_B588,
    cmd_help_B58F,
    cmd_help_6B97,
    cmd_help_B58A,
    cmd_help_73DF,
    cmd_help_7A79,
    cmd_help_B586,
    cmd_help_4069,
    cmd_help_C745,
    cmd_help_13B4,
    cmd_help_398B,
    cmd_help_47B4,
    cmd_help_B0B4,
    cmd_help_74CB,
    cmd_help_7D54,
};

static const uint16_t help_hashes[] CONSOLE_PROGMEM = {
    0xB58B,
    0x73DE,
    0x658F,
    0x66C9,
    0xB508,
    0x9F9C,
    0x5C2C,
    0x90B7,
    0xB58E,
    0xB588,
    0xB58F,
    0x6B97,
    0xB58A,
    0x73DF,
    0x7A79,
    0xB586,
    0x4069,
    0xC745,
    0x13B4,
    0x398B,
    0x47B4,
    0xB0B4,
    0x74CB,
    0x7D54,
};

