.PHONY: clean All

All:
	@echo "----------Building project:[ desktop - Debug ]----------"
	@cd "desktop" && "$(MAKE)" -f  "desktop.mk"
clean:
	@echo "----------Cleaning project:[ desktop - Debug ]----------"
	@cd "desktop" && "$(MAKE)" -f  "desktop.mk" clean
